####
#
# Create a base image for building web+java properties. Add support for nodeJS, NPM, and mvn
#
####
FROM alpine:3.12

# add mvn, npm, nodejs, hugo
RUN apk add --update --no-cache\
  openjdk11-jre \
  npm \
  nodejs \
  nghttp2 \
  maven \
  wget \
  tar

WORKDIR /tmp
RUN wget -qO- https://github.com/gohugoio/hugo/releases/download/v0.62.2/hugo_0.62.2_Linux-64bit.tar.gz | tar xvz -C /bin/

ENTRYPOINT [ "/bin/sh" ]